# Generated by Django 5.2.4 on 2025-07-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estimated_duration', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('base_priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('max_capacity', models.PositiveIntegerField(default=100)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queue_system.service')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('maintenance', 'Maintenance')], default='closed', max_length=20)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('current_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('services', models.ManyToManyField(related_name='counters', to='queue_system.service')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('called', 'Appelé'), ('in_service', 'En service'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='waiting', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('estimated_wait_time', models.PositiveIntegerField(default=0, help_text="Temps d'attente en minutes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queue_system.counter')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_system.service')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queue_system.ticket')),
            ],
        ),
    ]
