# Generated by Django 5.2.4 on 2025-07-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='countdown_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
